# Generated by Django 4.1.3 on 2022-12-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adoration', '0003_package_packagedetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='Title',
            new_name='title',
        ),
    ]
